name: Workflow template for CI jobs for Prover Components
on:
  workflow_call:

jobs:
  unit-tests:
    runs-on: [matterlabs-ci-runner]

    steps:
      - name: Prepare environment
        run: |
          sudo apt update && sudo apt install -y \
            pkg-config libclang-dev build-essential lldb lld \
            clang openssl libssl-dev gcc g++ pkg-config libclang-dev curl wget

      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
        with:
          submodules: "recursive"

      - name: Setup environment
        run: |
          echo ZKSYNC_HOME=$(pwd) >> $GITHUB_ENV
          echo $(pwd)/bin >> $GITHUB_PATH
          echo IN_DOCKER=1 >> .env

      - name: Start services
        env:
          RUNNER_COMPOSE_FILE: "docker-compose-runner-nightly.yml"
        run: |
          docker-compose -f ${RUNNER_COMPOSE_FILE} pull
          docker-compose -f ${RUNNER_COMPOSE_FILE} up --build -d zk
          ci_run sccache --start-server

      - name: Init
        run: |
          ci_run zk
          ci_run zk config compile
          ci_run zk db setup

      - name: Prover unit tests
        run: |
          # Not all tests are enabled since, prover and setup_key_generator_and_server requires bellman-cuda to be present
          ci_run zk f cargo test --release -p zksync_witness_generator -p vk_setup_data_generator_server_fri -p zksync_prover_fri -p zksync_witness_vector_generator -p zksync_prover_fri_utils
